//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbfinanceEntities : DbContext
    {
        public dbfinanceEntities()
            : base("name=dbfinanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<BankDetails> BankDetails { get; set; }
        public virtual DbSet<Card> Card { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<EMICard> EMICard { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Register> Register { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
    
        public virtual ObjectResult<string> sp_AdminLoginCheck(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_AdminLoginCheck", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_CreditDetails_Result> sp_CreditDetails(Nullable<int> cardNumber)
        {
            var cardNumberParameter = cardNumber.HasValue ?
                new ObjectParameter("cardNumber", cardNumber) :
                new ObjectParameter("cardNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CreditDetails_Result>("sp_CreditDetails", cardNumberParameter);
        }
    
        public virtual ObjectResult<sp_GetAllRegister_Result> sp_GetAllRegister()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllRegister_Result>("sp_GetAllRegister");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_LastTransactionDate(string username, Nullable<int> productId)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_LastTransactionDate", usernameParameter, productIdParameter);
        }
    
        public virtual ObjectResult<sp_UserLoginCheck_Result> sp_UserLoginCheck(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_UserLoginCheck_Result>("sp_UserLoginCheck", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_UserProducts_Result> sp_UserProducts(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_UserProducts_Result>("sp_UserProducts", usernameParameter);
        }
    
        public virtual ObjectResult<sp_UserProductWithId_Result> sp_UserProductWithId(string username, Nullable<int> productId)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_UserProductWithId_Result>("sp_UserProductWithId", usernameParameter, productIdParameter);
        }
    
        public virtual ObjectResult<sp_UserTransactions_Result> sp_UserTransactions(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_UserTransactions_Result>("sp_UserTransactions", usernameParameter);
        }
    }
}
